version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/next-app"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "America/New_York"

  - package-ecosystem: "npm"
    directory: "/express-api"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "America/New_York"
